### PR TITLE
Fix styling of reviews page so it's legible

### PR DESCRIPTION
**Pull request by r1chardj0n3s**
Fixes a few invalidities in the HTML, incorrectly used styles (l-content-page etc.) and adds in some container/container-fluids to fix some layout issues. 

Changes review pages to use content_inner block instead of body since that was blatting all of the reviews base.html which was clearly not desired. Very broken.

Also fix the front page so it's not white-on-black any longer.

### CODE REVIEW

**Review by n6151h — COMMENTED** [review]
There is already jumbotron-white in pyconau.CSS that has these (color) settings.

**Comment by r1chardj0n3s** [comment]
I would like to remove all use of the black jumbotron, please.

**Comment by n6151h** [comment]
Just to be clear, we're only gonna have jumbotron (ditching -white) henceforth?

**Comment by r1chardj0n3s** [comment]
Yes, I think that's a good idea, I just didn't want to confuse that change with this change.

**Pull request merged**
